# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model_user_ad.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import model_count_feature_pb2 as model__count__feature__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='model_user_ad.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13model_user_ad.proto\x1a\x19model_count_feature.proto\"\xc7\x03\n\x0bUserAdCount\x12,\n\ruser_id_ad_id\x18\x01 \x01(\x0b\x32\x15.BusinessCountFeature\x12\x36\n\x17user_id_ad_package_name\x18\x02 \x01(\x0b\x32\x15.BusinessCountFeature\x12:\n\x1buser_id_ad_package_category\x18\x03 \x01(\x0b\x32\x15.BusinessCountFeature\x12\x33\n\x14user_id_pos_id_ad_id\x18\x04 \x01(\x0b\x32\x15.BusinessCountFeature\x12=\n\x1euser_id_pos_id_ad_package_name\x18\x05 \x01(\x0b\x32\x15.BusinessCountFeature\x12+\n\x0cuser_id_c_id\x18\x06 \x01(\x0b\x32\x15.BusinessCountFeature\x12\x32\n\x13user_id_pos_id_c_id\x18\x07 \x01(\x0b\x32\x15.BusinessCountFeature\x12\x41\n\"user_id_pos_id_ad_package_category\x18\x08 \x01(\x0b\x32\x15.BusinessCountFeature\"4\n\rUserAdFeature\x12#\n\ruser_ad_count\x18\x01 \x01(\x0b\x32\x0c.UserAdCountb\x06proto3'
  ,
  dependencies=[model__count__feature__pb2.DESCRIPTOR,])




_USERADCOUNT = _descriptor.Descriptor(
  name='UserAdCount',
  full_name='UserAdCount',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id_ad_id', full_name='UserAdCount.user_id_ad_id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_id_ad_package_name', full_name='UserAdCount.user_id_ad_package_name', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_id_ad_package_category', full_name='UserAdCount.user_id_ad_package_category', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_id_pos_id_ad_id', full_name='UserAdCount.user_id_pos_id_ad_id', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_id_pos_id_ad_package_name', full_name='UserAdCount.user_id_pos_id_ad_package_name', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_id_c_id', full_name='UserAdCount.user_id_c_id', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_id_pos_id_c_id', full_name='UserAdCount.user_id_pos_id_c_id', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_id_pos_id_ad_package_category', full_name='UserAdCount.user_id_pos_id_ad_package_category', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=506,
)


_USERADFEATURE = _descriptor.Descriptor(
  name='UserAdFeature',
  full_name='UserAdFeature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_ad_count', full_name='UserAdFeature.user_ad_count', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=508,
  serialized_end=560,
)

_USERADCOUNT.fields_by_name['user_id_ad_id'].message_type = model__count__feature__pb2._BUSINESSCOUNTFEATURE
_USERADCOUNT.fields_by_name['user_id_ad_package_name'].message_type = model__count__feature__pb2._BUSINESSCOUNTFEATURE
_USERADCOUNT.fields_by_name['user_id_ad_package_category'].message_type = model__count__feature__pb2._BUSINESSCOUNTFEATURE
_USERADCOUNT.fields_by_name['user_id_pos_id_ad_id'].message_type = model__count__feature__pb2._BUSINESSCOUNTFEATURE
_USERADCOUNT.fields_by_name['user_id_pos_id_ad_package_name'].message_type = model__count__feature__pb2._BUSINESSCOUNTFEATURE
_USERADCOUNT.fields_by_name['user_id_c_id'].message_type = model__count__feature__pb2._BUSINESSCOUNTFEATURE
_USERADCOUNT.fields_by_name['user_id_pos_id_c_id'].message_type = model__count__feature__pb2._BUSINESSCOUNTFEATURE
_USERADCOUNT.fields_by_name['user_id_pos_id_ad_package_category'].message_type = model__count__feature__pb2._BUSINESSCOUNTFEATURE
_USERADFEATURE.fields_by_name['user_ad_count'].message_type = _USERADCOUNT
DESCRIPTOR.message_types_by_name['UserAdCount'] = _USERADCOUNT
DESCRIPTOR.message_types_by_name['UserAdFeature'] = _USERADFEATURE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserAdCount = _reflection.GeneratedProtocolMessageType('UserAdCount', (_message.Message,), {
  'DESCRIPTOR' : _USERADCOUNT,
  '__module__' : 'model_user_ad_pb2'
  # @@protoc_insertion_point(class_scope:UserAdCount)
  })
_sym_db.RegisterMessage(UserAdCount)

UserAdFeature = _reflection.GeneratedProtocolMessageType('UserAdFeature', (_message.Message,), {
  'DESCRIPTOR' : _USERADFEATURE,
  '__module__' : 'model_user_ad_pb2'
  # @@protoc_insertion_point(class_scope:UserAdFeature)
  })
_sym_db.RegisterMessage(UserAdFeature)


# @@protoc_insertion_point(module_scope)
