# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store_table.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import model_count_feature_pb2 as model__count__feature__pb2
import model_ad_pb2 as model__ad__pb2
import model_user_pb2 as model__user__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='store_table.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11store_table.proto\x1a\x19model_count_feature.proto\x1a\x0emodel_ad.proto\x1a\x10model_user.proto\"\xa7\x01\n\x10StoreUserCounter\x12\x43\n\x12store_user_counter\x18\x01 \x03(\x0b\x32\'.StoreUserCounter.StoreUserCounterEntry\x1aN\n\x15StoreUserCounterEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12$\n\x05value\x18\x02 \x01(\x0b\x32\x15.BusinessCountFeature:\x02\x38\x01\"V\n\x10StoreUserProfile\x12\x1c\n\tuser_base\x18\x01 \x01(\x0b\x32\t.UserBase\x12$\n\ruser_behavior\x18\x02 \x01(\x0b\x32\r.UserBehavior\"\x9d\x01\n\x0eStoreAdCounter\x12=\n\x10store_ad_counter\x18\x01 \x03(\x0b\x32#.StoreAdCounter.StoreAdCounterEntry\x1aL\n\x13StoreAdCounterEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12$\n\x05value\x18\x02 \x01(\x0b\x32\x15.BusinessCountFeature:\x02\x38\x01\"s\n\x0bStoreAdInfo\x12+\n\x08\x61\x64_infos\x18\x01 \x03(\x0b\x32\x19.StoreAdInfo.AdInfosEntry\x1a\x37\n\x0c\x41\x64InfosEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x16\n\x05value\x18\x02 \x01(\x0b\x32\x07.AdInfo:\x02\x38\x01\x62\x06proto3'
  ,
  dependencies=[model__count__feature__pb2.DESCRIPTOR,model__ad__pb2.DESCRIPTOR,model__user__pb2.DESCRIPTOR,])




_STOREUSERCOUNTER_STOREUSERCOUNTERENTRY = _descriptor.Descriptor(
  name='StoreUserCounterEntry',
  full_name='StoreUserCounter.StoreUserCounterEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='StoreUserCounter.StoreUserCounterEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='StoreUserCounter.StoreUserCounterEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=172,
  serialized_end=250,
)

_STOREUSERCOUNTER = _descriptor.Descriptor(
  name='StoreUserCounter',
  full_name='StoreUserCounter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='store_user_counter', full_name='StoreUserCounter.store_user_counter', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_STOREUSERCOUNTER_STOREUSERCOUNTERENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=250,
)


_STOREUSERPROFILE = _descriptor.Descriptor(
  name='StoreUserProfile',
  full_name='StoreUserProfile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_base', full_name='StoreUserProfile.user_base', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_behavior', full_name='StoreUserProfile.user_behavior', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=252,
  serialized_end=338,
)


_STOREADCOUNTER_STOREADCOUNTERENTRY = _descriptor.Descriptor(
  name='StoreAdCounterEntry',
  full_name='StoreAdCounter.StoreAdCounterEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='StoreAdCounter.StoreAdCounterEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='StoreAdCounter.StoreAdCounterEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=422,
  serialized_end=498,
)

_STOREADCOUNTER = _descriptor.Descriptor(
  name='StoreAdCounter',
  full_name='StoreAdCounter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='store_ad_counter', full_name='StoreAdCounter.store_ad_counter', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_STOREADCOUNTER_STOREADCOUNTERENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=341,
  serialized_end=498,
)


_STOREADINFO_ADINFOSENTRY = _descriptor.Descriptor(
  name='AdInfosEntry',
  full_name='StoreAdInfo.AdInfosEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='StoreAdInfo.AdInfosEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='StoreAdInfo.AdInfosEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=560,
  serialized_end=615,
)

_STOREADINFO = _descriptor.Descriptor(
  name='StoreAdInfo',
  full_name='StoreAdInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ad_infos', full_name='StoreAdInfo.ad_infos', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_STOREADINFO_ADINFOSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=500,
  serialized_end=615,
)

_STOREUSERCOUNTER_STOREUSERCOUNTERENTRY.fields_by_name['value'].message_type = model__count__feature__pb2._BUSINESSCOUNTFEATURE
_STOREUSERCOUNTER_STOREUSERCOUNTERENTRY.containing_type = _STOREUSERCOUNTER
_STOREUSERCOUNTER.fields_by_name['store_user_counter'].message_type = _STOREUSERCOUNTER_STOREUSERCOUNTERENTRY
_STOREUSERPROFILE.fields_by_name['user_base'].message_type = model__user__pb2._USERBASE
_STOREUSERPROFILE.fields_by_name['user_behavior'].message_type = model__user__pb2._USERBEHAVIOR
_STOREADCOUNTER_STOREADCOUNTERENTRY.fields_by_name['value'].message_type = model__count__feature__pb2._BUSINESSCOUNTFEATURE
_STOREADCOUNTER_STOREADCOUNTERENTRY.containing_type = _STOREADCOUNTER
_STOREADCOUNTER.fields_by_name['store_ad_counter'].message_type = _STOREADCOUNTER_STOREADCOUNTERENTRY
_STOREADINFO_ADINFOSENTRY.fields_by_name['value'].message_type = model__ad__pb2._ADINFO
_STOREADINFO_ADINFOSENTRY.containing_type = _STOREADINFO
_STOREADINFO.fields_by_name['ad_infos'].message_type = _STOREADINFO_ADINFOSENTRY
DESCRIPTOR.message_types_by_name['StoreUserCounter'] = _STOREUSERCOUNTER
DESCRIPTOR.message_types_by_name['StoreUserProfile'] = _STOREUSERPROFILE
DESCRIPTOR.message_types_by_name['StoreAdCounter'] = _STOREADCOUNTER
DESCRIPTOR.message_types_by_name['StoreAdInfo'] = _STOREADINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StoreUserCounter = _reflection.GeneratedProtocolMessageType('StoreUserCounter', (_message.Message,), {

  'StoreUserCounterEntry' : _reflection.GeneratedProtocolMessageType('StoreUserCounterEntry', (_message.Message,), {
    'DESCRIPTOR' : _STOREUSERCOUNTER_STOREUSERCOUNTERENTRY,
    '__module__' : 'store_table_pb2'
    # @@protoc_insertion_point(class_scope:StoreUserCounter.StoreUserCounterEntry)
    })
  ,
  'DESCRIPTOR' : _STOREUSERCOUNTER,
  '__module__' : 'store_table_pb2'
  # @@protoc_insertion_point(class_scope:StoreUserCounter)
  })
_sym_db.RegisterMessage(StoreUserCounter)
_sym_db.RegisterMessage(StoreUserCounter.StoreUserCounterEntry)

StoreUserProfile = _reflection.GeneratedProtocolMessageType('StoreUserProfile', (_message.Message,), {
  'DESCRIPTOR' : _STOREUSERPROFILE,
  '__module__' : 'store_table_pb2'
  # @@protoc_insertion_point(class_scope:StoreUserProfile)
  })
_sym_db.RegisterMessage(StoreUserProfile)

StoreAdCounter = _reflection.GeneratedProtocolMessageType('StoreAdCounter', (_message.Message,), {

  'StoreAdCounterEntry' : _reflection.GeneratedProtocolMessageType('StoreAdCounterEntry', (_message.Message,), {
    'DESCRIPTOR' : _STOREADCOUNTER_STOREADCOUNTERENTRY,
    '__module__' : 'store_table_pb2'
    # @@protoc_insertion_point(class_scope:StoreAdCounter.StoreAdCounterEntry)
    })
  ,
  'DESCRIPTOR' : _STOREADCOUNTER,
  '__module__' : 'store_table_pb2'
  # @@protoc_insertion_point(class_scope:StoreAdCounter)
  })
_sym_db.RegisterMessage(StoreAdCounter)
_sym_db.RegisterMessage(StoreAdCounter.StoreAdCounterEntry)

StoreAdInfo = _reflection.GeneratedProtocolMessageType('StoreAdInfo', (_message.Message,), {

  'AdInfosEntry' : _reflection.GeneratedProtocolMessageType('AdInfosEntry', (_message.Message,), {
    'DESCRIPTOR' : _STOREADINFO_ADINFOSENTRY,
    '__module__' : 'store_table_pb2'
    # @@protoc_insertion_point(class_scope:StoreAdInfo.AdInfosEntry)
    })
  ,
  'DESCRIPTOR' : _STOREADINFO,
  '__module__' : 'store_table_pb2'
  # @@protoc_insertion_point(class_scope:StoreAdInfo)
  })
_sym_db.RegisterMessage(StoreAdInfo)
_sym_db.RegisterMessage(StoreAdInfo.AdInfosEntry)


_STOREUSERCOUNTER_STOREUSERCOUNTERENTRY._options = None
_STOREADCOUNTER_STOREADCOUNTERENTRY._options = None
_STOREADINFO_ADINFOSENTRY._options = None
# @@protoc_insertion_point(module_scope)
