# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model_ad.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import model_count_feature_pb2 as model__count__feature__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='model_ad.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0emodel_ad.proto\x1a\x19model_count_feature.proto\".\n\x08\x43reative\x12\x13\n\x0b\x63reative_id\x18\x01 \x01(\t\x12\r\n\x05\x63p_id\x18\x02 \x01(\t\"\xe8\x01\n\x06\x41\x64Info\x12\r\n\x05\x61\x64_id\x18\x01 \x01(\x03\x12\x0e\n\x06\x61pp_id\x18\x02 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x03 \x01(\t\x12\x1c\n\tcreatives\x18\x04 \x03(\x0b\x32\t.Creative\x12\x15\n\rattr_platform\x18\x05 \x01(\x03\x12\x18\n\x10is_auto_download\x18\x06 \x01(\x03\x12\x13\n\x0b\x63reative_id\x18\x07 \x01(\t\x12\r\n\x05\x63p_id\x18\x08 \x01(\t\x12\x1c\n\x14\x63reative_create_time\x18\t \x01(\x03\x12\x1c\n\x14\x64\x61y_attr_install_cap\x18\n \x01(\x05\"\x83\x03\n\x07\x41\x64\x43ount\x12$\n\x05\x61\x64_id\x18\x01 \x01(\x0b\x32\x15.BusinessCountFeature\x12.\n\x0f\x61\x64_package_name\x18\x02 \x01(\x0b\x32\x15.BusinessCountFeature\x12\x32\n\x13\x61\x64_package_category\x18\x03 \x01(\x0b\x32\x15.BusinessCountFeature\x12+\n\x0cpos_id_ad_id\x18\x04 \x01(\x0b\x32\x15.BusinessCountFeature\x12\x35\n\x16pos_id_ad_package_name\x18\x05 \x01(\x0b\x32\x15.BusinessCountFeature\x12#\n\x04\x63_id\x18\x06 \x01(\x0b\x32\x15.BusinessCountFeature\x12*\n\x0bpos_id_c_id\x18\x07 \x01(\x0b\x32\x15.BusinessCountFeature\x12\x39\n\x1apos_id_ad_package_category\x18\x08 \x01(\x0b\x32\x15.BusinessCountFeature\"@\n\x06\x41\x64\x44\x61ta\x12\x18\n\x07\x61\x64_info\x18\x01 \x01(\x0b\x32\x07.AdInfo\x12\x1c\n\nad_counter\x18\x02 \x01(\x0b\x32\x08.AdCountb\x06proto3'
  ,
  dependencies=[model__count__feature__pb2.DESCRIPTOR,])




_CREATIVE = _descriptor.Descriptor(
  name='Creative',
  full_name='Creative',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='creative_id', full_name='Creative.creative_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cp_id', full_name='Creative.cp_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=91,
)


_ADINFO = _descriptor.Descriptor(
  name='AdInfo',
  full_name='AdInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ad_id', full_name='AdInfo.ad_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='app_id', full_name='AdInfo.app_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='category', full_name='AdInfo.category', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='creatives', full_name='AdInfo.creatives', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='attr_platform', full_name='AdInfo.attr_platform', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_auto_download', full_name='AdInfo.is_auto_download', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='creative_id', full_name='AdInfo.creative_id', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cp_id', full_name='AdInfo.cp_id', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='creative_create_time', full_name='AdInfo.creative_create_time', index=8,
      number=9, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='day_attr_install_cap', full_name='AdInfo.day_attr_install_cap', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=326,
)


_ADCOUNT = _descriptor.Descriptor(
  name='AdCount',
  full_name='AdCount',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ad_id', full_name='AdCount.ad_id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ad_package_name', full_name='AdCount.ad_package_name', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ad_package_category', full_name='AdCount.ad_package_category', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pos_id_ad_id', full_name='AdCount.pos_id_ad_id', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pos_id_ad_package_name', full_name='AdCount.pos_id_ad_package_name', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='c_id', full_name='AdCount.c_id', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pos_id_c_id', full_name='AdCount.pos_id_c_id', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pos_id_ad_package_category', full_name='AdCount.pos_id_ad_package_category', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=329,
  serialized_end=716,
)


_ADDATA = _descriptor.Descriptor(
  name='AdData',
  full_name='AdData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ad_info', full_name='AdData.ad_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ad_counter', full_name='AdData.ad_counter', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=718,
  serialized_end=782,
)

_ADINFO.fields_by_name['creatives'].message_type = _CREATIVE
_ADCOUNT.fields_by_name['ad_id'].message_type = model__count__feature__pb2._BUSINESSCOUNTFEATURE
_ADCOUNT.fields_by_name['ad_package_name'].message_type = model__count__feature__pb2._BUSINESSCOUNTFEATURE
_ADCOUNT.fields_by_name['ad_package_category'].message_type = model__count__feature__pb2._BUSINESSCOUNTFEATURE
_ADCOUNT.fields_by_name['pos_id_ad_id'].message_type = model__count__feature__pb2._BUSINESSCOUNTFEATURE
_ADCOUNT.fields_by_name['pos_id_ad_package_name'].message_type = model__count__feature__pb2._BUSINESSCOUNTFEATURE
_ADCOUNT.fields_by_name['c_id'].message_type = model__count__feature__pb2._BUSINESSCOUNTFEATURE
_ADCOUNT.fields_by_name['pos_id_c_id'].message_type = model__count__feature__pb2._BUSINESSCOUNTFEATURE
_ADCOUNT.fields_by_name['pos_id_ad_package_category'].message_type = model__count__feature__pb2._BUSINESSCOUNTFEATURE
_ADDATA.fields_by_name['ad_info'].message_type = _ADINFO
_ADDATA.fields_by_name['ad_counter'].message_type = _ADCOUNT
DESCRIPTOR.message_types_by_name['Creative'] = _CREATIVE
DESCRIPTOR.message_types_by_name['AdInfo'] = _ADINFO
DESCRIPTOR.message_types_by_name['AdCount'] = _ADCOUNT
DESCRIPTOR.message_types_by_name['AdData'] = _ADDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Creative = _reflection.GeneratedProtocolMessageType('Creative', (_message.Message,), {
  'DESCRIPTOR' : _CREATIVE,
  '__module__' : 'model_ad_pb2'
  # @@protoc_insertion_point(class_scope:Creative)
  })
_sym_db.RegisterMessage(Creative)

AdInfo = _reflection.GeneratedProtocolMessageType('AdInfo', (_message.Message,), {
  'DESCRIPTOR' : _ADINFO,
  '__module__' : 'model_ad_pb2'
  # @@protoc_insertion_point(class_scope:AdInfo)
  })
_sym_db.RegisterMessage(AdInfo)

AdCount = _reflection.GeneratedProtocolMessageType('AdCount', (_message.Message,), {
  'DESCRIPTOR' : _ADCOUNT,
  '__module__' : 'model_ad_pb2'
  # @@protoc_insertion_point(class_scope:AdCount)
  })
_sym_db.RegisterMessage(AdCount)

AdData = _reflection.GeneratedProtocolMessageType('AdData', (_message.Message,), {
  'DESCRIPTOR' : _ADDATA,
  '__module__' : 'model_ad_pb2'
  # @@protoc_insertion_point(class_scope:AdData)
  })
_sym_db.RegisterMessage(AdData)


# @@protoc_insertion_point(module_scope)
