# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model_user.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import model_count_feature_pb2 as model__count__feature__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='model_user.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10model_user.proto\x1a\x19model_count_feature.proto\"v\n\x0cUserBehavior\x12\x19\n\x11\x63lick_ad_app_list\x18\x01 \x03(\t\x12\x1b\n\x13install_ad_app_list\x18\x02 \x03(\t\x12\x18\n\x10install_app_list\x18\x03 \x03(\t\x12\x14\n\x0cuse_app_list\x18\x04 \x03(\t\"3\n\tUserCount\x12&\n\x07user_id\x18\x01 \x01(\x0b\x32\x15.BusinessCountFeature\"X\n\x08UserBase\x12\x0f\n\x07\x63ountry\x18\x01 \x01(\t\x12\x10\n\x08province\x18\x02 \x01(\t\x12\x0c\n\x04\x63ity\x18\x03 \x01(\t\x12\x0e\n\x06gender\x18\x04 \x01(\t\x12\x0b\n\x03\x61ge\x18\x05 \x01(\t\"\x84\x01\n\x0bUserProfile\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x1c\n\tuser_base\x18\x02 \x01(\x0b\x32\t.UserBase\x12$\n\ruser_behavior\x18\x03 \x01(\x0b\x32\r.UserBehavior\x12 \n\x0cuser_counter\x18\x04 \x01(\x0b\x32\n.UserCountb\x06proto3'
  ,
  dependencies=[model__count__feature__pb2.DESCRIPTOR,])




_USERBEHAVIOR = _descriptor.Descriptor(
  name='UserBehavior',
  full_name='UserBehavior',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='click_ad_app_list', full_name='UserBehavior.click_ad_app_list', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='install_ad_app_list', full_name='UserBehavior.install_ad_app_list', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='install_app_list', full_name='UserBehavior.install_app_list', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='use_app_list', full_name='UserBehavior.use_app_list', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=165,
)


_USERCOUNT = _descriptor.Descriptor(
  name='UserCount',
  full_name='UserCount',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='UserCount.user_id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=167,
  serialized_end=218,
)


_USERBASE = _descriptor.Descriptor(
  name='UserBase',
  full_name='UserBase',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='country', full_name='UserBase.country', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='province', full_name='UserBase.province', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='city', full_name='UserBase.city', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gender', full_name='UserBase.gender', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='age', full_name='UserBase.age', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=220,
  serialized_end=308,
)


_USERPROFILE = _descriptor.Descriptor(
  name='UserProfile',
  full_name='UserProfile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='UserProfile.user_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_base', full_name='UserProfile.user_base', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_behavior', full_name='UserProfile.user_behavior', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_counter', full_name='UserProfile.user_counter', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=311,
  serialized_end=443,
)

_USERCOUNT.fields_by_name['user_id'].message_type = model__count__feature__pb2._BUSINESSCOUNTFEATURE
_USERPROFILE.fields_by_name['user_base'].message_type = _USERBASE
_USERPROFILE.fields_by_name['user_behavior'].message_type = _USERBEHAVIOR
_USERPROFILE.fields_by_name['user_counter'].message_type = _USERCOUNT
DESCRIPTOR.message_types_by_name['UserBehavior'] = _USERBEHAVIOR
DESCRIPTOR.message_types_by_name['UserCount'] = _USERCOUNT
DESCRIPTOR.message_types_by_name['UserBase'] = _USERBASE
DESCRIPTOR.message_types_by_name['UserProfile'] = _USERPROFILE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserBehavior = _reflection.GeneratedProtocolMessageType('UserBehavior', (_message.Message,), {
  'DESCRIPTOR' : _USERBEHAVIOR,
  '__module__' : 'model_user_pb2'
  # @@protoc_insertion_point(class_scope:UserBehavior)
  })
_sym_db.RegisterMessage(UserBehavior)

UserCount = _reflection.GeneratedProtocolMessageType('UserCount', (_message.Message,), {
  'DESCRIPTOR' : _USERCOUNT,
  '__module__' : 'model_user_pb2'
  # @@protoc_insertion_point(class_scope:UserCount)
  })
_sym_db.RegisterMessage(UserCount)

UserBase = _reflection.GeneratedProtocolMessageType('UserBase', (_message.Message,), {
  'DESCRIPTOR' : _USERBASE,
  '__module__' : 'model_user_pb2'
  # @@protoc_insertion_point(class_scope:UserBase)
  })
_sym_db.RegisterMessage(UserBase)

UserProfile = _reflection.GeneratedProtocolMessageType('UserProfile', (_message.Message,), {
  'DESCRIPTOR' : _USERPROFILE,
  '__module__' : 'model_user_pb2'
  # @@protoc_insertion_point(class_scope:UserProfile)
  })
_sym_db.RegisterMessage(UserProfile)


# @@protoc_insertion_point(module_scope)
