# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model_count_feature.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='model_count_feature.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19model_count_feature.proto\"\x92\x04\n\x14\x42usinessCountFeature\x12\x43\n\x11\x63ount_features_7d\x18\x01 \x01(\x0b\x32(.BusinessCountFeature.ActionCountFeature\x12\x44\n\x12\x63ount_features_14d\x18\x02 \x01(\x0b\x32(.BusinessCountFeature.ActionCountFeature\x12\x44\n\x12\x63ount_features_30d\x18\x03 \x01(\x0b\x32(.BusinessCountFeature.ActionCountFeature\x12\x43\n\x11\x63ount_features_1d\x18\x04 \x01(\x0b\x32(.BusinessCountFeature.ActionCountFeature\x12\x43\n\x11\x63ount_features_3d\x18\x05 \x01(\x0b\x32(.BusinessCountFeature.ActionCountFeature\x12\x46\n\x14\x63ount_features_bj_3d\x18\x06 \x01(\x0b\x32(.BusinessCountFeature.ActionCountFeature\x1aW\n\x12\x41\x63tionCountFeature\x12\x0b\n\x03imp\x18\x01 \x01(\x05\x12\r\n\x05\x63lick\x18\x02 \x01(\x05\x12\x0f\n\x07install\x18\x03 \x01(\x05\x12\x14\n\x0c\x61ttr_install\x18\x04 \x01(\x05\x62\x06proto3'
)




_BUSINESSCOUNTFEATURE_ACTIONCOUNTFEATURE = _descriptor.Descriptor(
  name='ActionCountFeature',
  full_name='BusinessCountFeature.ActionCountFeature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='imp', full_name='BusinessCountFeature.ActionCountFeature.imp', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='click', full_name='BusinessCountFeature.ActionCountFeature.click', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='install', full_name='BusinessCountFeature.ActionCountFeature.install', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='attr_install', full_name='BusinessCountFeature.ActionCountFeature.attr_install', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=473,
  serialized_end=560,
)

_BUSINESSCOUNTFEATURE = _descriptor.Descriptor(
  name='BusinessCountFeature',
  full_name='BusinessCountFeature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='count_features_7d', full_name='BusinessCountFeature.count_features_7d', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='count_features_14d', full_name='BusinessCountFeature.count_features_14d', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='count_features_30d', full_name='BusinessCountFeature.count_features_30d', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='count_features_1d', full_name='BusinessCountFeature.count_features_1d', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='count_features_3d', full_name='BusinessCountFeature.count_features_3d', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='count_features_bj_3d', full_name='BusinessCountFeature.count_features_bj_3d', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_BUSINESSCOUNTFEATURE_ACTIONCOUNTFEATURE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=560,
)

_BUSINESSCOUNTFEATURE_ACTIONCOUNTFEATURE.containing_type = _BUSINESSCOUNTFEATURE
_BUSINESSCOUNTFEATURE.fields_by_name['count_features_7d'].message_type = _BUSINESSCOUNTFEATURE_ACTIONCOUNTFEATURE
_BUSINESSCOUNTFEATURE.fields_by_name['count_features_14d'].message_type = _BUSINESSCOUNTFEATURE_ACTIONCOUNTFEATURE
_BUSINESSCOUNTFEATURE.fields_by_name['count_features_30d'].message_type = _BUSINESSCOUNTFEATURE_ACTIONCOUNTFEATURE
_BUSINESSCOUNTFEATURE.fields_by_name['count_features_1d'].message_type = _BUSINESSCOUNTFEATURE_ACTIONCOUNTFEATURE
_BUSINESSCOUNTFEATURE.fields_by_name['count_features_3d'].message_type = _BUSINESSCOUNTFEATURE_ACTIONCOUNTFEATURE
_BUSINESSCOUNTFEATURE.fields_by_name['count_features_bj_3d'].message_type = _BUSINESSCOUNTFEATURE_ACTIONCOUNTFEATURE
DESCRIPTOR.message_types_by_name['BusinessCountFeature'] = _BUSINESSCOUNTFEATURE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BusinessCountFeature = _reflection.GeneratedProtocolMessageType('BusinessCountFeature', (_message.Message,), {

  'ActionCountFeature' : _reflection.GeneratedProtocolMessageType('ActionCountFeature', (_message.Message,), {
    'DESCRIPTOR' : _BUSINESSCOUNTFEATURE_ACTIONCOUNTFEATURE,
    '__module__' : 'model_count_feature_pb2'
    # @@protoc_insertion_point(class_scope:BusinessCountFeature.ActionCountFeature)
    })
  ,
  'DESCRIPTOR' : _BUSINESSCOUNTFEATURE,
  '__module__' : 'model_count_feature_pb2'
  # @@protoc_insertion_point(class_scope:BusinessCountFeature)
  })
_sym_db.RegisterMessage(BusinessCountFeature)
_sym_db.RegisterMessage(BusinessCountFeature.ActionCountFeature)


# @@protoc_insertion_point(module_scope)
